global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'learning-platform'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
